backend:
  name: github
  repo: clickme001/hibb-news
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "newsletters"
    label: "Newsletters"
    folder: "content/newsletters"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Content", name: "body", widget: "markdown" }
  - name: "news"
    label: "News"
    editor:
      component: "rich-text"